# Minimal Nginx config for static Next.js app
worker_processes 1;

# Store PID in /tmp (always writable)
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Disable logging to avoid permission issues
    access_log off;
    error_log  /dev/stderr;

    # Optimize static file serving
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;

    # 从宿主机访问时，需要关闭绝对重定向和端口在定向，否则会导致404错误，
    # 比如宿主机用8000 访问 nginx 8080 端口，
    # 页面url 会变成 http://localhost:8000/about 变成 http://localhost:8080/about/ ，导致404错误
    # 不加下面配置的话，宿主机只能用8080端口访问
    absolute_redirect off;
    port_in_redirect off;

    # Gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 256;

    server {
        listen       8080;
        server_name  localhost;

        # Serve static files
        root /usr/share/nginx/html;
        index index.html;

        # Handle Next.js static export routing
        # See: https://nextjs.org/docs/app/guides/static-exports#deploying
        location / {
            try_files $uri $uri.html $uri/ =404;
        }

        # This is necessary when `trailingSlash: false` (default).
        # You can omit this when `trailingSlash: true` in next.config.
        # Handles nested routes like /blog/post -> /blog/post.html
        # 当前开启了trailingSlash: true
        # https://nextjs.org/docs/app/api-reference/config/next-config-js/trailingSlash
        # 如果是静态路由，打包结果是 /blog/post/index.html，需要注释掉这里的配置
        # location ~ ^/(.+)/$ {
        #     rewrite ^/(.+)/$ /$1.html break;
        # }

        # Serve Next.js static assets
        location ~ ^/_next/ {
            try_files $uri =404;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        # Optional 404 handling
        error_page 404 /404.html;
        location = /404.html {
            internal;
        }
    }
}